// [dept, number, title, blurb]
export type CourseSource = readonly [string, number, string, string];

export const HUMANITIES: readonly CourseSource[] = [
  ["ARTH", 110, "Looking at Paintings", "How to read composition, color and brushwork, with weekly visits to the college gallery."],
  ["ARTH", 214, "Architecture of the Modern City", "Skyscrapers, housing blocks and parks from 1850 to now, and the arguments behind them."],
  ["ARTH", 260, "Photography and Truth", "From daguerreotypes to deepfakes: what photographs have been trusted to prove."],
  ["ARTH", 331, "Medieval Manuscripts", "Hands-on work with facsimiles of illuminated books and the workshops that made them."],
  ["ENGL", 101, "Writing About Anything", "A first-year writing seminar built around short essays on topics you choose."],
  ["ENGL", 145, "The Short Story", "Chekhov to Carmen Maria Machado, read closely and written about often."],
  ["ENGL", 232, "Shakespeare's Comedies", "Six comedies, read aloud in class and staged in scenes at the end of term."],
  ["ENGL", 278, "Writing for Radio and Podcasts", "Script, record and edit three short audio pieces."],
  ["ENGL", 340, "The Novel After 1945", "Postwar fiction in English and in translation, and how the form kept changing."],
  ["HIST", 120, "The World Since 1900", "A survey of the century's wars, empires, migrations and technologies."],
  ["HIST", 205, "Food in History", "What people ate, who grew it, and how trade in spices, sugar and grain reshaped the world."],
  ["HIST", 238, "The Silk Roads", "Merchants, monks and armies crossing Eurasia between 200 BCE and 1400 CE."],
  ["HIST", 312, "Cities in Revolt", "Paris 1871, Petrograd 1917, Prague 1968: urban uprisings and what followed."],
  ["PHIL", 101, "Big Questions", "Free will, knowledge, mind and morality, argued in short weekly papers."],
  ["PHIL", 210, "Ethics of Technology", "Privacy, automation and responsibility, with cases from current news."],
  ["PHIL", 225, "Logic and Argument", "Formal logic from truth tables to proofs, and how to spot a bad argument."],
  ["PHIL", 318, "Philosophy of Mind", "Consciousness, perception and whether machines could think."],
  ["MUSC", 105, "Listening to Music", "No experience needed. Learn to hear form, texture and harmony across genres."],
  ["MUSC", 150, "Choir", "Rehearse and perform two concerts. Open to all voices, no audition."],
  ["MUSC", 247, "Songwriting", "Write, workshop and record original songs in a small group."],
];

export const SCIENCES: readonly CourseSource[] = [
  ["BIOL", 101, "Cells and Genes", "How cells work and how traits are inherited, with a weekly lab."],
  ["BIOL", 115, "Biology of Food", "Fermentation, crops and nutrition, taught through kitchen experiments."],
  ["BIOL", 202, "Ecology", "Populations, communities and ecosystems, with field trips to the river reserve."],
  ["BIOL", 230, "Human Physiology", "How organ systems keep the body in balance, and what happens when they fail."],
  ["BIOL", 251, "Microbiology", "Bacteria, viruses and fungi, grown and identified in lab."],
  ["BIOL", 315, "Neurobiology", "From ion channels to circuits and behavior."],
  ["BIOL", 340, "Evolution", "Natural selection, drift and the evidence in genomes and fossils."],
  ["CHEM", 101, "General Chemistry I", "Atoms, bonds and reactions, with a weekly lab."],
  ["CHEM", 102, "General Chemistry II", "Equilibrium, kinetics and thermodynamics, with a weekly lab."],
  ["CHEM", 120, "Chemistry in the Kitchen", "Why bread rises and sauces split. Lab sessions in the teaching kitchen."],
  ["CHEM", 210, "Organic Chemistry I", "Structure and reactivity of carbon compounds."],
  ["CHEM", 245, "Environmental Chemistry", "Air, water and soil chemistry, and measuring pollution."],
  ["CHEM", 310, "Biochemistry", "Proteins, enzymes and metabolism."],
  ["CS", 101, "Introduction to Programming", "Learn Python by building small games and data tools. No experience needed."],
  ["CS", 112, "Programming for Designers", "Make interactive sketches and web pages in JavaScript."],
  ["CS", 150, "Discrete Structures", "Sets, logic, graphs and counting, the math behind computing."],
  ["CS", 201, "Data Structures", "Lists, trees, hash tables and graphs, and when to use each."],
  ["CS", 214, "Computer Systems", "How programs run on real hardware: memory, processes and C."],
  ["CS", 230, "Human-Computer Interaction", "Design, prototype and test interfaces with real people."],
  ["CS", 245, "Databases", "Relational modeling, SQL and how databases store data."],
  ["CS", 260, "Machine Learning", "Regression, classification and neural networks, with Python projects."],
  ["CS", 312, "Algorithms", "Design and analysis of efficient algorithms."],
  ["CS", 330, "Computer Graphics", "Rendering, shading and animation from first principles."],
  ["CS", 345, "Operating Systems", "Scheduling, memory and file systems, with a kernel project."],
  ["MATH", 110, "Calculus I", "Limits, derivatives and their uses."],
  ["MATH", 111, "Calculus II", "Integrals, series and differential equations."],
  ["MATH", 140, "Statistics", "Describing data, probability and inference, using R."],
  ["MATH", 155, "Mathematics of Games", "Probability, strategy and fairness through games and puzzles."],
  ["MATH", 220, "Linear Algebra", "Vectors, matrices and transformations, with applications to data."],
  ["MATH", 240, "Probability", "Random variables, distributions and limit theorems."],
  ["MATH", 310, "Real Analysis", "A rigorous look at the foundations of calculus."],
  ["MATH", 325, "Number Theory", "Primes, congruences and cryptography."],
  ["PHYS", 101, "Physics I: Mechanics", "Motion, forces and energy, with a weekly lab."],
  ["PHYS", 102, "Physics II: Electricity and Magnetism", "Fields, circuits and waves, with a weekly lab."],
  ["PHYS", 125, "Astronomy", "Planets, stars and galaxies. Includes evening telescope sessions."],
  ["PHYS", 140, "Physics of Music", "Sound, resonance and how instruments make their tones."],
  ["PHYS", 210, "Modern Physics", "Relativity and the beginnings of quantum mechanics."],
  ["PHYS", 250, "Electronics Lab", "Build and measure analog and digital circuits."],
  ["PHYS", 315, "Quantum Mechanics", "Wavefunctions, operators and the hydrogen atom."],
  ["PHYS", 330, "Climate Physics", "Radiation, energy balance and climate models."],
];

export const SOCIAL: readonly CourseSource[] = [
  ["ANTH", 101, "Being Human", "What anthropology can say about kinship, ritual, exchange and belief."],
  ["ANTH", 210, "Anthropology of Money", "Debt, gifts and currencies from shell money to crypto."],
  ["ANTH", 245, "Ethnographic Fieldwork", "Plan and carry out a small field study in the city."],
  ["ANTH", 320, "Medicine and Culture", "How illness and healing are understood in different societies."],
  ["ECON", 101, "Principles of Microeconomics", "Markets, prices and incentives."],
  ["ECON", 102, "Principles of Macroeconomics", "Growth, inflation, unemployment and policy."],
  ["ECON", 210, "Behavioral Economics", "How real people depart from rational choice, and why it matters."],
  ["ECON", 225, "Economics of Cities", "Housing, transit and why cities grow where they do."],
  ["ECON", 240, "Econometrics", "Regression and causal inference with real datasets."],
  ["ECON", 310, "Development Economics", "Poverty, aid and growth in low-income countries."],
  ["ECON", 335, "Game Theory", "Strategic decision-making, from auctions to arms races."],
  ["POLS", 101, "Introduction to Politics", "Power, institutions and how governments make decisions."],
  ["POLS", 150, "Elections and Voting", "Why people vote the way they do, and how elections are run."],
  ["POLS", 215, "International Relations", "War, trade and cooperation between states."],
  ["POLS", 230, "Constitutional Law", "Landmark cases on speech, equality and federal power."],
  ["POLS", 320, "Politics of the Internet", "Platforms, misinformation and regulation."],
  ["PSYC", 101, "Introduction to Psychology", "Perception, memory, emotion, development and disorders."],
  ["PSYC", 120, "Psychology of Sleep", "Why we sleep, what dreams are, and how to sleep better."],
  ["PSYC", 205, "Research Methods", "Design and run a small experiment and write it up."],
  ["PSYC", 220, "Social Psychology", "Conformity, persuasion, prejudice and helping."],
  ["PSYC", 235, "Developmental Psychology", "How children think, learn and grow."],
  ["PSYC", 260, "Cognitive Psychology", "Attention, memory, language and decision-making."],
  ["PSYC", 310, "Psychology of Music", "How we perceive, remember and feel music."],
  ["PSYC", 330, "Clinical Psychology", "Assessment and treatment of psychological disorders."],
  ["SOCI", 101, "Introduction to Sociology", "Class, race, gender and the institutions that shape lives."],
  ["SOCI", 140, "Sociology of Work", "Jobs, gig work and what people want from work."],
  ["SOCI", 215, "Cities and Neighborhoods", "Segregation, gentrification and community in the city."],
  ["SOCI", 230, "Sociology of Food", "Who eats what, and what that says about class and culture."],
  ["SOCI", 250, "Migration", "Who moves, why, and what happens when they arrive."],
  ["SOCI", 312, "Social Networks", "How ties between people shape jobs, health and ideas."],
];

export const INSTRUCTORS = [
  "Amara Okafor", "Ben Lindqvist", "Carmen Ruiz", "David Chen", "Elena Petrova", "Farid Haddad",
  "Grace Kim", "Hugo Martin", "Ines Duarte", "James Whitfield", "Kenji Sato", "Laila Rahman",
  "Marcus Bell", "Nadia Kowalski", "Owen Price", "Priya Natarajan", "Quinn Murphy", "Rosa Delgado",
  "Samuel Adeyemi", "Tara Walsh", "Uma Iyer", "Victor Novak", "Wen Li", "Yara Haddad", "Zoe Fischer",
];

export const BUILDINGS = ["Ames Hall", "Birch Library", "Corwin Lab", "Dalton Center", "Easton Hall", "Fenwick Studio"];

export const DEPT_NAMES: Record<string, string> = {
  ARTH: "Art History", ENGL: "English", HIST: "History", PHIL: "Philosophy", MUSC: "Music",
  BIOL: "Biology", CHEM: "Chemistry", CS: "Computer Science", MATH: "Mathematics", PHYS: "Physics",
  ANTH: "Anthropology", ECON: "Economics", POLS: "Political Science", PSYC: "Psychology", SOCI: "Sociology",
};
